@echo off
REM ****************************************************************************
REM Vivado (TM) v2020.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Mon Jul 14 21:01:12 +0530 2025
REM SW Build 3064766 on Wed Nov 18 09:12:45 MST 2020
REM
REM Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim full_subtractor_behav -key {Behavioral:sim_1:Functional:full_subtractor} -tclbatch full_subtractor.tcl -view C:/Users/nages/verilog_projects/Combinational Circuits/Subtractors/half_subtractor_behav.wcfg -log simulate.log"
call xsim  full_subtractor_behav -key {Behavioral:sim_1:Functional:full_subtractor} -tclbatch full_subtractor.tcl -view C:/Users/nages/verilog_projects/Combinational Circuits/Subtractors/half_subtractor_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
