# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/nages/verilog_projects/FFT64pt_fixed_point/FFT64pt_fixed_point.srcs/sources_1/ip/xfft_1_new/xfft_1_new.xci
# IP: The module: 'xfft_1_new' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/nages/verilog_projects/FFT64pt_fixed_point/FFT64pt_fixed_point.gen/sources_1/ip/xfft_1_new/xfft_1_new_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'xfft_1_new'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/nages/verilog_projects/FFT64pt_fixed_point/FFT64pt_fixed_point.srcs/sources_1/ip/xfft_1_new/xfft_1_new.xci
# IP: The module: 'xfft_1_new' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/nages/verilog_projects/FFT64pt_fixed_point/FFT64pt_fixed_point.gen/sources_1/ip/xfft_1_new/xfft_1_new_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'xfft_1_new'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
