# - repo: local
#   hooks:
#     - id: update-requirements
#       name: Update requirements.txt with pipreqs
#       entry: pipreqs .
#       language: system
#       pass_filenames: false
#       stages: [commit]
