# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/nages/verilog_projects/FFT-IP/FFT-IP.srcs/sources_1/ip/fft_64/fft_64.xci
# IP: The module: 'fft_64' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/nages/verilog_projects/FFT-IP/FFT-IP.gen/sources_1/ip/fft_64/fft_64_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fft_64'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/nages/verilog_projects/FFT-IP/FFT-IP.srcs/sources_1/ip/fft_64/fft_64.xci
# IP: The module: 'fft_64' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/nages/verilog_projects/FFT-IP/FFT-IP.gen/sources_1/ip/fft_64/fft_64_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fft_64'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
