# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/nages/verilog_projects/FFT-IP/FFT-IP.srcs/sources_1/ip/floating_point_multiplication/floating_point_multiplication.xci
# IP: The module: 'floating_point_multiplication' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/nages/verilog_projects/FFT-IP/FFT-IP.gen/sources_1/ip/floating_point_multiplication/floating_point_multiplication_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'floating_point_multiplication'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/nages/verilog_projects/FFT-IP/FFT-IP.srcs/sources_1/ip/floating_point_multiplication/floating_point_multiplication.xci
# IP: The module: 'floating_point_multiplication' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/nages/verilog_projects/FFT-IP/FFT-IP.gen/sources_1/ip/floating_point_multiplication/floating_point_multiplication_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'floating_point_multiplication'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
