# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/nages/verilog_projects/FFT/FFT.srcs/sources_1/ip/xfft_1/xfft_1.xci
# IP: The module: 'xfft_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/nages/verilog_projects/FFT/FFT.gen/sources_1/ip/xfft_1/xfft_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'xfft_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/nages/verilog_projects/FFT/FFT.srcs/sources_1/ip/xfft_1/xfft_1.xci
# IP: The module: 'xfft_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/nages/verilog_projects/FFT/FFT.gen/sources_1/ip/xfft_1/xfft_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'xfft_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
