webtalk_init -webtalk_dir C:/Users/nages/verilog_projects/FFT64pt_fixed_point/FFT64pt_fixed_point.sim/sim_1/behav/xsim/xsim.dir/tb_FFT_fixed_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Fri Sep  5 20:01:30 2025" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3064766" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "212824581_0_0_168" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "351d6f81-0428-4cc3-9a7a-28ba5a9981ff" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "5fed6875f46b4b15becee567cd4bc433" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "7" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 5 5600U with Radeon Graphics         " -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2296 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "2" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "2735 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.61_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "26944_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2515489709 -regid "212824581_0_0_168" -xml C:/Users/nages/verilog_projects/FFT64pt_fixed_point/FFT64pt_fixed_point.sim/sim_1/behav/xsim/xsim.dir/tb_FFT_fixed_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/nages/verilog_projects/FFT64pt_fixed_point/FFT64pt_fixed_point.sim/sim_1/behav/xsim/xsim.dir/tb_FFT_fixed_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/nages/verilog_projects/FFT64pt_fixed_point/FFT64pt_fixed_point.sim/sim_1/behav/xsim/xsim.dir/tb_FFT_fixed_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
